#gpt evaluator.py 
"""
Docstring for evaluator
Rubric:
Rubric: 
Rank the technical depth  : 
1 ( Beginner : syntax fix ,basic, how do I,..  ), 
2 ( Intermediate: prototype, simple project like todo list. ) ,
3 ( High Intermediate: optimization , production to 1000+, technical interview at company for work  ) 
Independence Level: 
1 ( Ask AI to generate code from scratch : can you write this ) 
2 (Ask AI  to debug, fully, fix) 
3 ( Ask AI to minor debug , minor fix ) 
- Does it mention any modern tech? Yes or no
- Mention ( AWS, firebase, Langgraph, etc.. ? ), mention what it is

"""


import os
import json
import pandas as pd
from openai import OpenAI
from dotenv import load_dotenv

# 1. Load Environment Variables

load_dotenv()

client = OpenAI(
    api_key=os.environ.get("OPENAI_API_KEY"),
)

def evaluate_question(question_text):
    """
    Evaluates a generated student question using GPT-4o based on a specific 
    academic rubric (mentionned above) for technical depth, independence, and modern tech stack usage.

    Args:
        question_text (str): The question generated by the student persona (MIT/Malagasy).

    Returns:
        dict: A dictionary containing the scores and reasoning.
    """
    
    # 2. Define the System Prompt (The Rubric)
    system_prompt = """
    You are an expert Computer Science educator and researcher acting as an impartial judge. 
    Your task is to evaluate a question asked by a CS student based on the following rubric.
    
    ### RUBRIC
    
    **1. Technical Depth (Rank 1-3)**
    - 1 (Beginner): Syntax fixes, basic "how-to", simple logic (e.g., loops, print statements).
    - 2 (Intermediate): Prototyping, simple projects (e.g., To-Do list), standard library usage.
    - 3 (High Intermediate): Optimization, production-scaling (1000+ users), system design, professional interview prep.

    **2. Independence Level (Rank 1-3)**
    - 1 (Dependent): Asks AI to generate code from scratch ("Can you write this?", "Give me code").
    - 2 (Guided): Asks AI to fully debug or fix a broken block ("Fix this error for me").
    - 3 (Independent): Asks for minor debugging, specific explanation, or conceptual feedback.

    **3. Modern Tech Detection**
    - Detect if the question explicitly mentions modern technologies (e.g., AWS, Firebase, LangChain, React, Docker, Kubernetes).
    - Standard languages (Python, Java) do NOT count as "Modern Tech" context unless a specific modern framework is used.
    
    ### OUTPUT FORMAT
    Return a pure JSON object with keys: 
    - "technical_depth_score" (int)
    - "independence_score" (int)
    - "has_modern_tech" (bool)
    - "modern_tech_list" (list of strings, e.g. ["AWS", "Next.js"])
    - "reasoning" (short string explaining the rating)
    """

    try:
        response = client.chat.completions.create(
            model="gpt-4o", 
            response_format={"type": "json_object"}, 
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Student Question to evaluate: \"{question_text}\""}
            ],
            temperature=0.0 
        )

        # Parse the JSON string from the response
        result_json = json.loads(response.choices[0].message.content)
        return result_json

    except Exception as e:
        print(f"Error evaluating question: {e}")
        return None

# --- MAIN EXECUTION BLOCK ---
if __name__ == "__main__":
    
    # Load the dataset from CSV
    data_path = "results/toEvaluate.csv"
    df_input = pd.read_csv(data_path)
    
    print(f"Starting evaluation of {len(df_input)} questions...\n")

    results = []

    # Iterate through all rows in the CSV
    for idx, row in df_input.iterrows():
        prompt_id = row['prompt_id']
        q_text = row['llm_generated_question']
        
        # Clean question text (remove extra quotes if present)
        q_text = str(q_text).strip().strip('"')
        
        print(f"Evaluating Question ID {prompt_id}: {q_text[:50]}...")
        
        # Call the evaluator
        scores = evaluate_question(q_text)
        
        if scores:
            # Combine the prompt_id, question, and scores
            combined_entry = {
                "prompt_id": prompt_id,
                "question": q_text,
                **scores
            }
            results.append(combined_entry)

    # Save to CSV
    df_results = pd.DataFrame(results)
    output_filename = "results/data_evaluationGPT.csv"
    df_results.to_csv(output_filename, index=False)
    
    print(f"\nSuccess! Results saved to {output_filename}")
    print(f"\nEvaluated {len(results)} questions")
    print("\nSample results:")
    print(df_results[["prompt_id", "technical_depth_score", "independence_score", "has_modern_tech"]].head(10))