# gpt_evaluator.py
"""
Question Evaluation System

This evaluator assesses AI-generated questions across four dimensions:
1. Technical Depth (0-4): Conceptual complexity and technical knowledge required
2. Cognitive Independence (1-4): Level of reasoning and decision-making expected
3. Technology Usage (0-3): How meaningfully modern technologies are referenced
4. Question Intent: Primary purpose of the question (categorical)

See the full rubric documentation for detailed scoring criteria.
"""

import os
import json
import pandas as pd
from openai import OpenAI
from dotenv import load_dotenv

# 1. Load Environment Variables
load_dotenv()

client = OpenAI(
    api_key=os.environ.get("OPENAI_API_KEY"),
)

def evaluate_question(question_text):
    """
    Evaluates a generated student question using GPT-4o based on a comprehensive
    academic rubric for technical depth, cognitive independence, technology usage,
    and question intent.

    Args:
        question_text (str): The question generated by the student persona (MIT/Malagasy).

    Returns:
        dict: A dictionary containing the scores and reasoning.
    """
    
    # 2. Define the System Prompt (The Rubric)
    system_prompt = """
    You are an expert Computer Science educator and researcher acting as an impartial judge. 
    Your task is to evaluate a question asked by a CS student based on the following rubric.
    
    ### RUBRIC
    
    **1. Technical Depth (0-4) - Conceptual Complexity**
    Measures the level of technical knowledge and abstraction required to meaningfully answer the question.
    
    - 0 (Non-Technical): No programming or technical concepts (e.g., clubs, career advice, pure definitions)
    - 1 (Foundational): Basic concepts, definitions, or syntax-level explanations (e.g., "What is frontend vs backend?")
    - 2 (Applied): Practical use of known tools, algorithms, or patterns; simple projects or standard problem-solving 
      (e.g., implementing WebSockets, basic dynamic programming)
    - 3 (Advanced): Optimization, system design, scalability, or tradeoffs; requires analysis beyond standard usage 
      (e.g., runtime optimization, architecture decisions)
    - 4 (Expert): Research-level or highly specialized knowledge; novel constraints, system internals, or theoretical depth 
      (e.g., distributed systems internals, compiler optimizations)

    **2. Cognitive Independence (1-4)**
    Measures how much reasoning, decision-making, and problem decomposition is expected from the question asker.
    
    - 1 (Outsourced Thinking): Requests full solutions or code generation with no constraints or reasoning provided 
      (e.g., "Write this program for me")
    - 2 (Guided Execution): Asks AI to implement, fix, or debug with limited analysis 
      (e.g., "Fix this bug", "Implement X using Y")
    - 3 (Analytical): Requests comparison, explanation of tradeoffs, or optimization reasoning 
      (e.g., "Which approach is better and why?")
    - 4 (Metacognitive): Reflects on strategy, learning process, or problem-solving approach 
      (e.g., "How should I approach solving these problems?")

    **3. Technology Usage (0-3)**
    Evaluates whether modern technologies are referenced and how meaningfully they are incorporated.
    Note: Standard languages (Python, Java) alone do NOT count as "modern tech" unless paired with specific modern frameworks.
    
    - 0 (None): No technologies or tools mentioned
    - 1 (Name-Dropping): Mentions tools or platforms without context or purpose (e.g., "Should I use AWS?")
    - 2 (Contextual Use): Technologies are tied to a specific function or problem 
      (e.g., WebSockets for real-time updates, Firebase for auth)
    - 3 (Architectural Awareness): Demonstrates understanding of limitations, scaling, or alternatives 
      (e.g., AWS IAM design, database tradeoffs)

    **4. Question Intent (Primary Purpose)**
    Classify the main goal of the question. Select ONLY ONE:
    
    - "Foundational Learning": Understanding basic concepts
    - "Problem-Solving/Implementation": Building or implementing a feature
    - "Optimization/Scaling": Improving performance, reliability, or scale
    - "Learning Strategy": Improving how one learns or prepares
    - "Career/Social": Networking, clubs, job preparation
    
    ### OUTPUT FORMAT
    Return a pure JSON object with keys: 
    - "technical_depth_score" (int, 0-4)
    - "cognitive_independence_score" (int, 1-4)
    - "technology_usage_score" (int, 0-3)
    - "technology_list" (list of strings, e.g., ["AWS", "Next.js"], empty list if none)
    - "question_intent" (string, one of the five categories above)
    - "reasoning" (string, 2-3 sentences explaining the ratings)
    
    ### IMPORTANT NOTES
    - Higher technical depth does not necessarily mean higher quality; intent matters.
    - Be precise in distinguishing between levels (e.g., Applied vs Advanced).
    - If a question spans multiple intents, choose the PRIMARY one.
    - Standard programming languages (Python, Java, C++) without specific frameworks count as tech_usage = 0.
    """

    try:
        response = client.chat.completions.create(
            model="gpt-4o", 
            response_format={"type": "json_object"}, 
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Student Question to evaluate: \"{question_text}\""}
            ],
            temperature=0.0 
        )

        # Parse the JSON string from the response
        result_json = json.loads(response.choices[0].message.content)
        return result_json

    except Exception as e:
        print(f"Error evaluating question: {e}")
        return None

# --- MAIN EXECUTION BLOCK ---
if __name__ == "__main__":
    
    # Load the dataset from CSV
    data_path = "results_gpt/toEvaluate.csv"
    df_input = pd.read_csv(data_path)
    
    print(f"Starting evaluation of {len(df_input)} questions...\n")

    results = []

    # Iterate through all rows in the CSV
    for idx, row in df_input.iterrows():
        prompt_id = row['prompt_id']
        q_text = row['llm_generated_question']
        
        # Clean question text (remove extra quotes if present)
        q_text = str(q_text).strip().strip('"')
        
        print(f"Evaluating Question ID {prompt_id}: {q_text[:80]}...")
        
        # Call the evaluator
        scores = evaluate_question(q_text)
        
        if scores:
            # Combine the prompt_id, question, and scores
            combined_entry = {
                "prompt_id": prompt_id,
                "question": q_text,
                **scores
            }
            results.append(combined_entry)
        else:
            print(f"  ⚠️  Failed to evaluate question {prompt_id}")

    # Save to CSV
    df_results = pd.DataFrame(results)
    output_filename = "results_gpt/data_evaluationGPT4D.csv"
    
    # Create results directory if it doesn't exist
    os.makedirs("results", exist_ok=True)
    
    df_results.to_csv(output_filename, index=False)
    
    print(f"\n{'='*60}")
    print(f"✅ Success! Results saved to {output_filename}")
    print(f"{'='*60}")
    print(f"\n📊 Evaluation Summary:")
    print(f"   Total questions evaluated: {len(results)}")
    
    if len(results) > 0:
        print(f"\n📈 Score Distributions:")
        print(f"   Technical Depth (0-4):")
        print(df_results['technical_depth_score'].value_counts().sort_index().to_string())
        print(f"\n   Cognitive Independence (1-4):")
        print(df_results['cognitive_independence_score'].value_counts().sort_index().to_string())
        print(f"\n   Technology Usage (0-3):")
        print(df_results['technology_usage_score'].value_counts().sort_index().to_string())
        print(f"\n   Question Intent:")
        print(df_results['question_intent'].value_counts().to_string())
        
        print(f"\n📋 Sample results (first 10):")
        sample_cols = ["prompt_id", "technical_depth_score", "cognitive_independence_score", 
                      "technology_usage_score", "question_intent"]
        print(df_results[sample_cols].head(10).to_string(index=False))